/haha:
  ros__parameters:
    background_b: 234
    background_g: 0
    background_r: 141
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
